[hewg]
version = "0.4.0-alpha.nd"
type = "library"

[project]
version = "0.0.0"
org = "crow"
name = "brbt"
description = "bounded red-black binary tree implementation"
authors = { }

[depends]
internal = { }
external = { }

[cxx]
flags = { "-Wall" "-Wextra" "-Werror" }
std = 23
sources = { }

[c]
flags = { "-Wall" "-Wextra" "-ggdb" }
std = 17
sources = { "brbt.c" }

[hooks.prebuild]
[hooks.postbuild]
